### ISSUE TITLE
Allow custom pgn to ankify

### ISSUE THREAD

**Issue by ExtremeCoolDude** [pwenker/chessli#10]
I have a large tactics database on pgn format  that is separated in individual chapters for each puzzle. The way this tool sounds, this should be possible in the current setup, any advice on how to do this ?

**Comment by ExtremeCoolDude** [comment]
Even better would be to allow usage of custom anki template which only contains fen and move list  fields for eg.

**Comment by pwenker** [comment]
Hey, can you provide an example of how your database of pgn files looks like? I guess in the current version it won't work, but maybe it can be extended with not much effort to make your use case working.

**Comment by ExtremeCoolDude** [comment]
They would be like these :

https://github.com/xinyangz/chess-tactics-pgn

http://gorgonian.weebly.com/uploads/1/7/2/2/17221082/auerswald.pgn

**Comment by pwenker** [comment]
Maybe [these](https://ankiweb.net/shared/info/1082754005) card templates are a better solution for you? 
The second pgn database you mentioned (auerswald collection) is already available for the above card templates [here](https://ankiweb.net/shared/info/2047046995). 
Or are the two sets you mentioned above just examples of how yours looks like? 
In any case, at the moment `chessli` is not able to ankify arbitrary pgn databases, but since the above shared decks exist and `chessli` makes available the > 1 million (and growing) lichess puzzle database, I would need to be convinced that this is a feature useful to be implemented.

**Comment by pwenker** [comment]
I close this here for now. @ExtremeCoolDude, just comment here if you have further questions. 
The "ankification" of arbitraty pgn sources is not possible at the moment, but I will try to tackle it in the future, see #5.

**Comment by D4V5** [comment]
Thank you for the reply. I looked at the above solutions, the card templates are excellent. 

More interesting is the template has only two pertinent fields, fen and pgn. Since anki decks can be imported as json , outputting two fields to a text file shouldn't be difficult: 

```
`  if games_by_user:
            for game_json, game_pgn in [
                (
                    game,
                    games_client.export(
                        game["id"],
                        literate="true",
                        as_pgn=True,
                        opening="true",
                        tags="true",
                        moves="true",
                        evals="true",
                    )
```

I'm sure I can output Fen and SAN  from somewhere around here.  I'll post if I figure something out. Thanks!

**Comment by ExtremeCoolDude** [comment]
I think I commented when I was logged in on another account xD, so I did try it but the chess py  library doesn't spit out { comments } nicely for the excellent templates, particularly if there are linebreaks on pgn comments, the linebreaks is included in the string, which is very hard to import into anki since anki treats each line as a separate card, other than that simply iterating over games and spitting out fen and SAN separated by tab with game on each line is enough to import into anki as a txt file.
