### ISSUE TITLE
chessli games ankify clarification on mistakes

### ISSUE THREAD

**Issue by nayyala** [pwenker/chessli#15]
I've played ~180 games in lichess. I ran "chessli games ankify --since forever" and only got mistakes from 2 games

I played 7 within the last week and the csv comes up completely empty.

I'm not at that level where I only have 2/180 games with mistakes :p I think there might be something up with it, unless i'm not understanding what constitutes a mistake

**Comment by pwenker** [comment]
Thanks for reporting the issue! 

1) First problem are empty csv files. I will add a check that if there are not mistakes found in a game, then no csv file should be created instead of an empty one.
2) Regarding the missing mistakes. There are two potential points: 
a) Chessli only finds mistakes for games that you (or your opponent) have analyzed on lichess. The reason is, that only then chessli can fetch an annotated pgn, which can then be parsed to find your mistakes. Admittedly, I didn't describe this in the docs, which I will do. I assume that this is the issue, can you please verify it? 
b) Also, at the moment there is a limit on the number of games you can fetch at once (set to 30, see the `--max` option). This is because lichess allows to fetch a maximum of 30 games per second and how the code is at the moment, you can try, but probably get an error if you try to set `--max` to a higher value. This might be solved in the future if needed, however, from a learning view point, I would recommend to only ankify recent games, as the workload will probably be large enough starting with the last 30 games.

**Comment by pwenker** [comment]
This is fixed with v0.2.3. 

Chessli now only creates csv files if they are non-empty and I added a note to the documentation [here](https://pwenker.com/chessli/tutorial/how_to_learn_from_your_games/) about the need to analyse games via lichess in order to find mistakes .
