### ISSUE TITLE
Feature request for option to import only incorrect  puzzles from lichess

### ISSUE THREAD

**Issue by ExtremeCoolDude** [pwenker/chessli#18]
Would save a lot of time.

**Comment by ExtremeCoolDude** [comment]
I tried adding a conditional for `puzzle_ids` to only append()  if `puzzle["ratingDiff"]` is negative on `tactics.py`, since I only need the incorrects, but can't figure out how to install the modified package from dir to see if it works. I keep getting `SetupTools` not found, and it says `SetupTools` already satisified if I try to install it.

**Comment by pwenker** [comment]
Hey, since it was faster to implement your feature request myself instead of guiding you through it, I took the liberty and publish `chessli 0.2.4` with it :) 

```
🔥 CHESSLI TACTICS 🔥

Usage: chessli tactics ankify [OPTIONS]

  Optionally fetch new puzzles and ankify them

Options:
  --new / --old                   Select whether to only ankify new puzzles or
                                  old puzzles  [default: True]

  --failed-only / --no-failed-only
                                  Select whether to only ankify puzzles that
                                  have been failed  [default: False]

  --won-only / --no-won-only      Select whether to only ankify puzzles that
                                  have been won  [default: False]

  --export-only / --directly      Select to only export the created anki cards
                                  [default: True]

  --help                          Show this message and exit.
  ```
  When you upgrade to v0.2.4 with `pip install --upgrade chessli` you should now be able to run `chessli tactics ankify --failed-only` 
  in order to only select those puzzles that you didn't manage to solve. 
  
  As a side note: there is a boolean `puzzle['win']` entry that tells you whether a puzzle was correctly solved or not, which I used in the implementation.

**Comment by ExtremeCoolDude** [comment]
Thanks a lot! 

I'm about 2-3 months into coding and don't know much, do you have any advice on setting up a workflow for tinkering with chessli ? I want to try something like sync with a specific deck with another versions of templates in anki.

**Comment by pwenker** [comment]
Hey, can you please open a new issue with your new question, since it is not related to the feature request? :) 
Then it will be easier for people to find the issue/solution when they have the same problems or ideas.
I will then answer in the new issue!

**Comment by ExtremeCoolDude** [comment]
Will do xD
