### ISSUE TITLE
[Question]  How to setup chessli  for testing and install from local directory 

### ISSUE THREAD

**Issue by ExtremeCoolDude** [pwenker/chessli#19]
Newish coder, how to setup chessli for tinkering purposes and also how to test tinkered features without breaking the pip install. Thanks for this awesome tool!

**Comment by pwenker** [comment]
In order to develop on chessli, the best workflow is to clone this repository and then `pip install` it from there instead of installing it from pipy. 

1. Clone the repository: `https://github.com/pwenker/chessli.git` 
2. Move into the folder and install it: `cd chessli && pip install .` 
3. Perform whatever changes you want to do.
4. Go back into the `chessli` folder and do `pip install .` 


Notes: 
- Unfortunately, I don't know of any more straightforward way, since I use `pyproject.toml` and `poetry` instead of `setup.py`. For the latter one, it is possible to install via `pip install -e .` so that you don't need to reinstall `chessli` after every single change that you want to test. There is an open issue: https://github.com/python-poetry/poetry/issues/34 
- I don't know how the above steps need to be adapted if you are a windows user.

Feel free to comment below, in case it works, or also if you encounter problems or have further questions :)

**Comment by pwenker** [comment]
@ExtremeCoolDude: Did it work for you?

**Comment by ExtremeCoolDude** [comment]
Got stuck in the first step tbh, I think its too basic problem but can't figure it out via google-fu.

`ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/da/chessli/chessli`

**Comment by pwenker** [comment]
Awesome. Happy coding :)
