### ISSUE TITLE
does anyone know of a way that i can download all of the FEN codes from a book in pdf form onto my computer?

### ISSUE THREAD

**Issue by marksteadman080592** [pwenker/chessli#21]

**Comment by pwenker** [comment]
Unfortunately, to the best of my knowledge, there is no generic and automatic way due to the unstructured nature of PDF's.
 
One thing you could try, however, is to look if you find a corresponding study e.g. on Lichess. For example, for Pandolfini's Endgame book there are some: https://lichess.org/study/EMudCdxu. In that case, you could just export/download all pgn's/fen's with one click.

**Comment by cshancock** [comment]
It seems like this person would be interested in this: https://ebook.chessvision.ai/

**Comment by marksteadman080592** [comment]
Hey there

I already know if that website. I was wondering if there was a way to do it
more quickly than just going diagram but diagram
